FROM $com.sap.opensuse.python36

RUN python3 -m pip --no-cache-dir install pandas

RUN python3 -m pip --no-cache-dir install fuzzywuzzy

RUN python3 -m pip --no-cache-dir install sklearn

RUN python3 -m pip --no-cache-dir install xgboost