FROM §/com.sap.datahub.linuxx86_64/sles:15.0-sap-003

RUN python3 -m pip --no-cache-dir install pandas

RUN python3 -m pip --no-cache-dir install fuzzywuzzy

RUN python3 -m pip --no-cache-dir install sklearn

RUN python3 -m pip --no-cache-dir install xgboost

RUN python3 -m pip --no-cache-dir install lightgbm

RUN python3 -m pip --no-cache-dir install sdi_utils
